"""Quarantine emitters: keep the build green WITHOUT deleting tests.

Philosophy (borrowed from the best CI teams): a quarantined test still
runs and still reports — it just can't fail the build. Deletion hides
signal; quarantine preserves it while unblocking everyone else.
"""

from __future__ import annotations

import re

_SAFE_K = re.compile(r"[A-Za-z0-9_:.\-\[\]]+\Z")


def _k_name(tid: str) -> tuple[str, bool]:
    """Short test name for -k expressions. Returns (name, is_safe).

    Unsafe names (spaces/quotes from parametrization) can't go in -k
    verbatim — callers must verify and prefer --deselect with node ids.
    We never silently mangle: mangling hides signal.
    """
    name = tid.split("::")[-1].split("[")[0]
    if _SAFE_K.fullmatch(name):
        return name, True
    return name, False


def _pytest_k_expression(ids: list[str]) -> tuple[str, list[str]]:
    shorts, risky = [], []
    for tid in ids:
        name, safe = _k_name(tid)
        shorts.append(name)
        if not safe:
            risky.append(tid)
    return "not " + " and not ".join(shorts), risky


def emit(framework: str, flaky_ids: list[str]) -> str:
    fw = framework.lower()
    if fw == "pytest":
        k, risky = _pytest_k_expression(flaky_ids)
        listed = "\n".join(f"#  - {tid}" for tid in flaky_ids)
        out = (
            "# Generated by `unflake quarantine --framework pytest` — review, don't blindly commit.\n"
            f"# Quarantined {len(flaky_ids)} flaky test(s):\n{listed}\n\n"
            "# Option A: exclude them from the gating run, keep them in a nightly non-gating run:\n"
            f"pytest -k \"{k}\"\n\n"
            "# Option B: run ONLY the quarantined set (nightly, non-gating, still reporting):\n"
            f"pytest -k \"{' or '.join(t.split('::')[-1].split('[')[0] for t in flaky_ids)}\" --junitxml=quarantine.xml\n"
        )
        if risky:
            out += ("\n# WARNING: these ids contain spaces/quotes and can't go in -k verbatim —\n"
                    "# verify the expression matches, or use `pytest --deselect <nodeid>`:\n"
                    + "".join(f"#  RISKY: {tid}\n" for tid in risky))
        return out
    if fw in {"jest", "vitest"}:
        arr = ",\n".join(f'  "{tid}"' for tid in flaky_ids)
        flag = "--testPathIgnorePatterns" if fw == "jest" else "--exclude"
        return (
            f"// Generated by `unflake quarantine --framework {fw}`\n"
            "// Quarantine list — wire into CI as a non-gating job, keep reporting.\n"
            f"export const QUARANTINED = [\n{arr}\n];\n\n"
            f"// CI tip ({fw}): run the gating suite excluding quarantine files,\n"
            f"// then run quarantine separately with `{flag}` inverted so it still reports.\n"
        )
    if fw == "playwright":
        joined = "|".join(t.split("::")[-1].split("[")[0] for t in flaky_ids)
        return (
            "# Generated by `unflake quarantine --framework playwright`\n"
            f"# Gating run excludes the {len(flaky_ids)} quarantined test(s):\n"
            f"npx playwright test --grep-invert \"{joined}\"\n\n"
            "# Nightly non-gating run (still reporting):\n"
            f"npx playwright test --grep \"{joined}\" --reporter=junit,html\n"
        )
    raise ValueError(f"unknown framework {framework!r} (try: pytest, jest, vitest, playwright)")


FRAMEWORKS = ("pytest", "jest", "vitest", "playwright")
